const page = () => {
  return (
    <>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
      <h1>Welcome to the Main Page</h1>
    </>
  );
};

export default page;
