export const docSpecialties = [
  { id: "doc-001", specialty: "Cardiology" },
  { id: "doc-002", specialty: "Dermatology" },
  { id: "doc-003", specialty: "Neurology" },
  { id: "doc-004", specialty: "Orthopedics" },
  { id: "doc-005", specialty: "Pediatrics" },
  { id: "doc-006", specialty: "Oncology" },
  { id: "doc-007", specialty: "Radiology" },
  { id: "doc-008", specialty: "Urology" },
  { id: "doc-009", specialty: "Psychiatry" },
  { id: "doc-010", specialty: "Gynecology" },
  { id: "doc-011", specialty: "Endocrinology" },
  { id: "doc-012", specialty: "Gastroenterology" },
  { id: "doc-013", specialty: "Nephrology" },
  { id: "doc-014", specialty: "Rheumatology" },
  { id: "doc-015", specialty: "Pulmonology" },
  { id: "doc-016", specialty: "Hematology" },
  { id: "doc-017", specialty: "Ophthalmology" },
  { id: "doc-018", specialty: "Allergy and Immunology" },
  { id: "doc-019", specialty: "Pathology" },
  { id: "doc-020", specialty: "Anesthesiology" },
];
